import JSZip from 'jszip'

type Platform = 'Web' | 'Mobile' | 'Both'

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'generated-app'
}

function escapeText(value: string) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

export async function downloadProjectZip(
  appName: string,
  summary: string,
  features: string[],
  platform: Platform,
) {
  const slug = slugify(appName)
  const safeName = escapeText(appName)
  const safeSummary = escapeText(summary)
  const selectedFeatures = features.slice(0, 6)
  const zip = new JSZip()
  const root = slug

  if (platform === 'Web' || platform === 'Both') {
    const featureMarkup = selectedFeatures.map((feature, index) =>
      '<article class="feature-card"><span>0' + (index + 1) + '</span><h2>' +
      escapeText(feature) +
      '</h2><p>Included in the first version of the product blueprint.</p></article>'
    ).join('\\n')

    const packageJson = JSON.stringify({
      name: slug,
      private: true,
      version: '0.1.0',
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { '@vitejs/plugin-react': '^6.1.1', vite: '^8.3.0', react: '^19.2.8', 'react-dom': '^19.2.8' },
    }, null, 2)

    const mainJsx = [
      "import React from 'react'",
      "import { createRoot } from 'react-dom/client'",
      "import './styles.css'",
      '',
      'const features = ' + JSON.stringify(selectedFeatures),
      '',
      'function App() {',
      '  return (',
      '    <main>',
      '      <header><strong>' + safeName + '</strong><nav><a>Home</a><a>Features</a><a>About</a></nav></header>',
      '      <section className="hero"><span>GENERATED FROM YOUR BLUEPRINT</span><h1>' + safeName + '</h1><p>' + safeSummary + '</p><button>Get started</button></section>',
      '      <section className="features">' + featureMarkup + '</section>',
      '      <footer><strong>' + safeName + '</strong><span>Built from the Build Your Own App blueprint.</span></footer>',
      '    </main>',
      '  )',
      '}',
      '',
      "createRoot(document.getElementById('root')).render(<App />)",
    ].join('\\n')

    const webCss = ':root{font-family:Inter,system-ui,sans-serif;color:#211b25;background:#f8f5fa}*{box-sizing:border-box}body{margin:0}main{max-width:1120px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;padding:16px 0}nav{display:flex;gap:20px;color:#6e6572}a{cursor:pointer}.hero{margin-top:48px;padding:72px 56px;border-radius:28px;background:linear-gradient(135deg,#e9f8fb,#f8eaff);border:1px solid #e5dce9}.hero span{font-size:12px;font-weight:800;letter-spacing:.14em;color:#a24e79}.hero h1{font-size:clamp(42px,7vw,76px);margin:14px 0 12px;letter-spacing:-.05em}.hero p{max-width:700px;color:#6f6672;font-size:18px;line-height:1.6}.hero button{margin-top:16px;padding:13px 20px;border:0;border-radius:12px;background:#25202b;color:#fff;font-weight:700}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.feature-card{padding:24px;border:1px solid #e4dce5;border-radius:20px;background:#fff}.feature-card span{font-size:11px;color:#a05fd0;font-weight:800}.feature-card h2{font-size:18px}.feature-card p{color:#7b717e;line-height:1.5}footer{display:flex;justify-content:space-between;padding:28px 0;color:#7b717e}@media(max-width:700px){.features{grid-template-columns:1fr}header{align-items:flex-start;gap:16px}nav{gap:10px}.hero{padding:40px 28px}}'

    zip.file(root + '/web/package.json', packageJson)
    zip.file(root + '/web/index.html', '<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>' + safeName + '</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>')
    zip.file(root + '/web/src/main.jsx', mainJsx)
    zip.file(root + '/web/src/styles.css', webCss)
    zip.file(root + '/web/README.md', '# ' + appName + '\\n\\nGenerated by Build Your Own App.\\n\\nPlatform: Web (React + Vite).\\n\\nRun: npm install, then npm run dev.\\n')
  }

  if (platform === 'Mobile' || platform === 'Both') {
    const mobilePackage = JSON.stringify({
      name: slug + '-mobile',
      version: '0.1.0',
      private: true,
      main: 'node_modules/expo/AppEntry.js',
      scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios', web: 'expo start --web' },
      dependencies: { expo: '^54.0.0', react: '^19.1.0', 'react-native': '^0.81.5' },
    }, null, 2)

    const mobileApp = [
      "import { StatusBar } from 'expo-status-bar'",
      "import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native'",
      '',
      'const features = ' + JSON.stringify(selectedFeatures),
      '',
      'export default function App() {',
      '  return (',
      '    <SafeAreaView style={styles.safe}>',
      '      <StatusBar style="dark" />',
      '      <ScrollView contentContainerStyle={styles.container}>',
      '        <Text style={styles.kicker}>GENERATED FROM YOUR BLUEPRINT</Text>',
      '        <Text style={styles.title}>' + safeName + '</Text>',
      '        <Text style={styles.summary}>' + safeSummary + '</Text>',
      '        <View style={styles.list}>',
      '          {features.map((feature, index) => (',
      '            <View key={feature} style={styles.card}>',
      '              <Text style={styles.number}>0{index + 1}</Text>',
      '              <Text style={styles.feature}>{feature}</Text>',
      '              <Text style={styles.note}>Included in the first version of the product blueprint.</Text>',
      '            </View>',
      '          ))}',
      '        </View>',
      '      </ScrollView>',
      '    </SafeAreaView>',
      '  )',
      '}',
      '',
      "const styles = StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f5fa'},container:{padding:24,paddingTop:48,paddingBottom:48},kicker:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#a24e79'},title:{fontSize:42,fontWeight:'800',color:'#211b25',marginTop:12},summary:{fontSize:17,lineHeight:25,color:'#6f6672',marginTop:12},list:{marginTop:28,gap:14},card:{backgroundColor:'#fff',borderRadius:18,padding:20,borderWidth:1,borderColor:'#e4dce5'},number:{fontSize:11,fontWeight:'800',color:'#a05fd0'},feature:{fontSize:18,fontWeight:'700',color:'#211b25',marginTop:8},note:{fontSize:14,lineHeight:20,color:'#7b717e',marginTop:6}})",
    ].join('\\n')

    zip.file(root + '/mobile/package.json', mobilePackage)
    zip.file(root + '/mobile/app.json', JSON.stringify({ expo: { name: appName, slug: slug, version: '1.0.0', orientation: 'portrait', userInterfaceStyle: 'light' } }, null, 2))
    zip.file(root + '/mobile/App.js', mobileApp)
    zip.file(root + '/mobile/README.md', '# ' + appName + ' — Mobile\\n\\nGenerated by Build Your Own App using Expo + React Native.\\n\\nRun: npm install, then npx expo start.\\n')
  }

  const rootReadme = platform === 'Both'
    ? '# ' + appName + '\\n\\nGenerated by Build Your Own App.\\n\\nWeb starter: web/README.md\\nMobile starter: mobile/README.md'
    : platform === 'Mobile'
      ? '# ' + appName + '\\n\\nGenerated mobile starter.\\n\\nSee mobile/README.md.'
      : '# ' + appName + '\\n\\nGenerated web starter.\\n\\nSee web/README.md.'

  zip.file(root + '/README.md', rootReadme)
  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = slug + '-source.zip'
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
